# Site wide configuration

title: Carlos is Awesome
description: Carlos Meza - DevOps, SysAdmin, Web Developer, Engineer
logo: # 120x120 px default image used for Twitter summary card
teaser: # 400x250 px default teaser image used in image archive grid
locale:
url:

# Jekyll configuration

sass:
    sass_dir: _sass
    style: compressed
permalink: /:categories/:title_:year-:month-:day/
kramdown:
  toc_levels: 1..2
highlighter: pygments
gems:
  - jekyll-sitemap


# Site owner
owner:
  name: Carlos Meza
  email: me@carlosmeza.com
  twitter: _digitalRoots
  linkedin: cmeza99
  bio: I'm awesome
  avatar: bio-photo.jpg # 160x160 px image for author byline
disqus-shortname:

google:
  tracking_id: UA-43721421-2
  ad-client:
  ad-slot:

exclude: ["lib", "config.rb", ".sass-cache", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "*.sublime-project", "*.sublime-workspace", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "node_modules", "Gruntfile.js", "package.json"]
