# Jekyll configuration

title: "Resume"
name: "Carlos Meza"
description: "Carlos Meza: DevOper, Infosecy, and just Awesome!"
email: contact@carlosmeza.com

# Url is currently only used only for the RSS feed in feed.xml
# url: http://localhost:4000

# For a project page here should be a project name. Otherwise (for user's/organizaion's page leave it empty)
baseurl: ''

social:
  twitter: digitalr00ts
  github: cmeza99
  stackoverflow:
  reddit:
  linkedin: cmeza99
  instagram:
  lastfm:

# Google Analytics key, leave blank to ignore
google_analytics_key:

permalink: /:year/:month/:title
paginate_path: "/activity/page:num/"
paginate: 10

# highlighter: pygments
# markdown: redcarpet
# redcarpet:
#  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]

exclude: ['README.md', 'LICENSE', 'Gemfile', 'Rakefile']

sass:
  style: compressed

gems:
- jekyll-mentions
- jekyll-redirect-from
  # - jekyll-sitemap
  # - jekyll-feed

# Rakefile settings
post:
  template: _post.txt
  extension: md
page:
  template: _page.txt
  extension: md
  editor: atom-beta
git:
    branch: gh-pages
# transfer:
#  command: rsync
#  settings: -av
#  source: _site/
#  destination: ~/Git/username.github.com/
